[[redirects]]
    from = "/api/submit"
    to = "https://multistepform-frontendmasters.onrender.com/api/submit"
    force = true
    headers = {X-From = "Netlify"}

[[headers]]
    for = "/api/submit"
    [headers.values] 
        Access-Control-Allow-Origin = "*"

[[redirects]]
    from = "/*"
    to = "/index.html"
    status = 200