[[redirects]]
    from = "/api/submit"
    to = "https://multistepform-frontendmasters.onrender.com/api/submit"
    force = true
    conditions = {Method = "POST"}

[[redirects]]
    from = "/api/*"
    to = "https://multistepform-frontendmasters.onrender.com/api/:splat"

[[redirects]]
    from = "/*"
    to = "/index.html"
    status = 200